apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-app
  namespace: test-ns01
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: apps/vm-app
    directory:
      recurse: true
  destination:
    server: 10.1.0.6
    namespace: test-ns01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
