apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-tier-app
  namespace: test-ns01
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: multi-tier/child-apps    
    directory:
      recurse: true   
  destination:
    server: 'https://10.1.0.6:443'
    namespace: test-ns01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
