apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-app
  namespace: testing123
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: apps/container-app
    directory:
      recurse: true
  destination:
    name: 'vks-01'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
