apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-app
  namespace: shared-svcs
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: multi-tier/apps/container-app
    directory:
      recurse: true
  destination:
    name: 'https://10.1.0.8:6443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
