apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-app
  namespace: shared-svcs
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: multi-tier/apps/vm-app
    directory:
      recurse: true
  destination:
    server: 'https://10.1.0.6:443'
    namespace: shared-svcs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
