apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-app
  namespace: demo-org-apps-kjl82
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: apps/vm-app
    directory:
      recurse: true
  destination:
    server: 'https://10.1.0.6:443'
    namespace: demo-org-apps-kjl82
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
