apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-tier-web
  namespace: demo-93hwn
spec:
  project: default
  source:
    repoURL: 'https://github.com/tkrausjr/vcf-argocd-gitops.git'
    targetRevision: main
    path: child-apps    
    directory:
      recurse: true   
  destination:
    server: 'https://10.1.8.6:443'
    namespace: demo-93hwn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
