apiVersion: v1
kind: Service
metadata:
  name: two-tier-nginx-svc
spec:
  selector:
    app: two-tier-pod-nginx
    type: argocd
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: LoadBalancer
